# Generated by Django 4.2.20 on 2025-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cuisine_type",
            field=models.CharField(
                choices=[
                            ("african", "African"),
                            ("american", "American"),
                            ("caribbean", "Caribbean"),
                            ("asian", "Asian"),
                            ("middle eastern", "Middle Eastern"),
                            ("chinese", "Chinese"),
                            ("indian", "Indian"),
                            ("pakistani", "Pakistani"),
                            ("indonesian", "Indonesian"),
                            ("european", "European"),
                            ("oceanic", "Oceanic"),
                ],
                default="african",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                ],
                default="Breakfast",
                max_length=50,
            ),
        ),
    ]
